export const AllUsersData = [
  {
    id: '1236',
    user_name: 'John Dan',
    password: 'fdvd!@#$sdf',
    phone_no: '+32 2143234',
    trade:['Plumbing','Electrical'],
    role: 'user',
    city: 'New York',
  },
  {
    id: '1237',
    user_name: 'Sarah Johnson',
    password: 'password123',  
    phone_no: '+1 555 1234',
      trade:['Carpentry','Painting'],
    role: 'Secretary',
    city: 'Los Angeles',
  },
  {
    id: '1238',
    user_name: 'Michael Chen',
    password: 'michael2024',
    phone_no: '+86 1234 5678',
      trade:['HVAC','Landscaping'],
    role: 'user',
    city: 'San Francisco',
  },
  {
    id: '1239',
    user_name: 'Emma Wilson',
    password: 'emma2024',

    phone_no: '+44 20 1234 5678',
    trade: ['Carpentry'],
    role: 'Secretary',
    city: 'London',
  },
  {
    id: '1240',
    user_name: 'Carlos Rodriguez',
    password: 'carlos2024',

    phone_no: '+34 123 456 789',
    trade: ['Plumbing'],
    role: 'user',
    city: 'Madrid',
  },
  {
    id: '1241',
    user_name: 'Fatima Ahmed',
    password: 'fatima2024',

    phone_no: '+20 123 4567 890',
    trade: ['Painting'],
    role: 'Secretary',
    city: 'Cairo',
  },
  {
    id: '1242',
    user_name: 'David Kim',
    password: 'david2024',

    phone_no: '+82 10 1234 5678',
    trade: ['Electrical'],
    role: 'user',
    city: 'Seoul',
  },
  {
    id: '1243',
    user_name: 'Lisa Anderson',
    password: 'lisa2024',
    phone_no: '+46 123 456 789',
    trade: ['Carpentry','Painting'],
    role: 'Secretary',
    city: 'Stockholm',
  },
  {
    id: '1244',
    user_name: 'Marco Rossi',
    password: 'marco2024',
    phone_no: '+39 123 456 7890',
    trade: ['Landscaping'],
    role: 'user',
    city: 'Rome',
  },
  {
    id: '1245',
    user_name: 'Anna Kowalski',
    password: 'anna2024',
    phone_no: '+48 123 456 789',
    trade: ['HVAC'],
    role: 'Secretary',
    city: 'Warsaw',
  },
  {
    id: '1246',
    user_name: 'James Smith',
    password: 'james2024',
    phone_no: '+61 2 1234 5678',
    trade: ['Landscaping'],
    role: 'user',
    city: 'Sydney',
  },
  {
    id: '1247',
    user_name: 'Maria Garcia',
    password: 'maria2024',
    phone_no: '+52 123 456 7890',
    trade: ['Plumbing','Electrical','Carpentry'],
    role: 'Secretary',
    city: 'Mexico City',
  },
  {
    id: '1248',
    user_name: 'Yuki Tanaka',
    password: 'yuki2024',
    phone_no: '+81 90 1234 5678',
    trade: ['Electrical'],
    role: 'user',
    city: 'Tokyo',
  },
  {
    id: '1249',
    user_name: 'Sophie Martin',
    password: 'sophie2024',
    phone_no: '+33 1 23 45 67 89',
    trade: ['Painting'],
    role: 'Secretary',
    city: 'Paris',
  },
  {
    id: '1250',
    user_name: 'Ahmed Hassan',
    password: 'ahmed2024',
    phone_no: '+971 50 123 4567',
    trade: ['Carpentry'],
    role: 'user',
    city: 'Dubai',
  }
];