const requestSupportData = [
    {
        id: '1336',
        user_name: 'John Doe',
        phone_no: '+32 2143234',
        city: 'Granada',
        supportReqDate: '26 Feb, 2026',
        status: 'Solved',
    },
    {
        id: '1337',
        user_name: 'Jane Smith',
        phone_no: '+44 1234567',
        city: 'London',
        supportReqDate: '25 Feb, 2026',
        status: 'Pending',
    },
    {
        id: '1338',
        user_name: 'Carlos Ruiz',
        phone_no: '+34 9876543',
        city: 'Madrid',
        supportReqDate: '24 Feb, 2026',
        status: 'Solved',
    },
    {
        id: '1339',
        user_name: 'Anna Müller',
        phone_no: '+49 1122334',
        city: 'Berlin',
        supportReqDate: '23 Feb, 2026',
        status: 'Pending',
    },
    {
        id: '1340',
        user_name: 'Luca Bianchi',
        phone_no: '+39 5566778',
        city: 'Rome',
        supportReqDate: '22 Feb, 2026',
        status: 'Solved',
    },
    {
        id: '1341',
        user_name: 'Marie Dubois',
        phone_no: '+33 9988776',
        city: 'Paris',
        supportReqDate: '21 Feb, 2026',
        status: 'Pending',
    },
    {
        id: '1342',
        user_name: 'Ivan Petrov',
        phone_no: '+7 1231231',
        city: 'Moscow',
        supportReqDate: '20 Feb, 2026',
        status: 'Solved',
    },
    {
        id: '1343',
        user_name: 'Sara Svensson',
        phone_no: '+46 3213213',
        city: 'Stockholm',
        supportReqDate: '19 Feb, 2026',
        status: 'Pending',
    },
    {
        id: '1344',
        user_name: 'Ali Hassan',
        phone_no: '+20 5556667',
        city: 'Cairo',
        supportReqDate: '18 Feb, 2026',
        status: 'Solved',
    },
    {
        id: '1345',
        user_name: 'Emily Clark',
        phone_no: '+1 2025551',
        city: 'New York',
        supportReqDate: '17 Feb, 2026',
        status: 'Pending',
    },
    {
        id: '1346',
        user_name: 'Pedro Silva',
        phone_no: '+55 9988776',
        city: 'São Paulo',
        supportReqDate: '16 Feb, 2026',
        status: 'Solved',
    },
    {
        id: '1347',
        user_name: 'Linda Lee',
        phone_no: '+82 1234567',
        city: 'Seoul',
        supportReqDate: '15 Feb, 2026',
        status: 'Pending',
    },
    {
        id: '1348',
        user_name: 'Ahmed Al-Farsi',
        phone_no: '+971 1122334',
        city: 'Dubai',
        supportReqDate: '14 Feb, 2026',
        status: 'Solved',
    },
    {
        id: '1349',
        user_name: 'Sophia Rossi',
        phone_no: '+39 2233445',
        city: 'Milan',
        supportReqDate: '13 Feb, 2026',
        status: 'Pending',
    },
    {
        id: '1350',
        user_name: 'David Kim',
        phone_no: '+82 7654321',
        city: 'Busan',
        supportReqDate: '12 Feb, 2026',
        status: 'Solved',
    },
]

export default requestSupportData;