export const rewardStatusData = [
    {
        id: 1234,
        user_name: 'Robert',
        recent_lead: '10 Feb, 2026',
        total_leads_sent_us: 200,
        total_gift_received: 50,
        last_gift_date: '10 Feb, 2026',
        last_gift_received: 'Gas Card',
        next_planned_gift: '15 Feb, 2026',
    },
    {
        id: 1235,
        user_name: 'Sophia',
        recent_lead: '12 Feb, 2026',
        total_leads_sent_us: 180,
        total_gift_received: 45,
        last_gift_date: '12 Feb, 2026',
        last_gift_received: 'Amazon Voucher',
        next_planned_gift: '17 Feb, 2026',
    },
    {
        id: 1236,
        user_name: 'Liam',
        recent_lead: '13 Feb, 2026',
        total_leads_sent_us: 150,
        total_gift_received: 40,
        last_gift_date: '13 Feb, 2026',
        last_gift_received: 'Coffee Mug',
        next_planned_gift: '18 Feb, 2026',
    },
    {
        id: 1237,
        user_name: 'Emma',
        recent_lead: '14 Feb, 2026',
        total_leads_sent_us: 170,
        total_gift_received: 42,
        last_gift_date: '14 Feb, 2026',
        last_gift_received: 'Gift Card',
        next_planned_gift: '19 Feb, 2026',
    },
    {
        id: 1238,
        user_name: 'Noah',
        recent_lead: '15 Feb, 2026',
        total_leads_sent_us: 210,
        total_gift_received: 55,
        last_gift_date: '15 Feb, 2026',
        last_gift_received: 'Bluetooth Speaker',
        next_planned_gift: '20 Feb, 2026',
    },
    {
        id: 1239,
        user_name: 'Olivia',
        recent_lead: '16 Feb, 2026',
        total_leads_sent_us: 160,
        total_gift_received: 38,
        last_gift_date: '16 Feb, 2026',
        last_gift_received: 'Movie Ticket',
        next_planned_gift: '21 Feb, 2026',
    },
    {
        id: 1240,
        user_name: 'William',
        recent_lead: '17 Feb, 2026',
        total_leads_sent_us: 140,
        total_gift_received: 35,
        last_gift_date: '17 Feb, 2026',
        last_gift_received: 'Book',
        next_planned_gift: '22 Feb, 2026',
    },
    {
        id: 1241,
        user_name: 'Ava',
        recent_lead: '18 Feb, 2026',
        total_leads_sent_us: 175,
        total_gift_received: 41,
        last_gift_date: '18 Feb, 2026',
        last_gift_received: 'Gift Basket',
        next_planned_gift: '23 Feb, 2026',
    },
    {
        id: 1242,
        user_name: 'James',
        recent_lead: '19 Feb, 2026',
        total_leads_sent_us: 190,
        total_gift_received: 48,
        last_gift_date: '19 Feb, 2026',
        last_gift_received: 'Headphones',
        next_planned_gift: '24 Feb, 2026',
    },
    {
        id: 1243,
        user_name: 'Mia',
        recent_lead: '20 Feb, 2026',
        total_leads_sent_us: 155,
        total_gift_received: 39,
        last_gift_date: '20 Feb, 2026',
        last_gift_received: 'Water Bottle',
        next_planned_gift: '25 Feb, 2026',
    },
    {
        id: 1244,
        user_name: 'Benjamin',
        recent_lead: '21 Feb, 2026',
        total_leads_sent_us: 165,
        total_gift_received: 43,
        last_gift_date: '21 Feb, 2026',
        last_gift_received: 'Fitness Band',
        next_planned_gift: '26 Feb, 2026',
    },
    {
        id: 1245,
        user_name: 'Charlotte',
        recent_lead: '22 Feb, 2026',
        total_leads_sent_us: 185,
        total_gift_received: 47,
        last_gift_date: '22 Feb, 2026',
        last_gift_received: 'Smart Plug',
        next_planned_gift: '27 Feb, 2026',
    },
    {
        id: 1246,
        user_name: 'Lucas',
        recent_lead: '23 Feb, 2026',
        total_leads_sent_us: 195,
        total_gift_received: 49,
        last_gift_date: '23 Feb, 2026',
        last_gift_received: 'Backpack',
        next_planned_gift: '28 Feb, 2026',
    },
    {
        id: 1247,
        user_name: 'Amelia',
        recent_lead: '24 Feb, 2026',
        total_leads_sent_us: 205,
        total_gift_received: 52,
        last_gift_date: '24 Feb, 2026',
        last_gift_received: 'Lunch Box',
        next_planned_gift: '29 Feb, 2026',
    },
    {
        id: 1248,
        user_name: 'Henry',
        recent_lead: '25 Feb, 2026',
        total_leads_sent_us: 220,
        total_gift_received: 56,
        last_gift_date: '25 Feb, 2026',
        last_gift_received: 'Gift Card',
        next_planned_gift: '01 Mar, 2026',
    },
]