export const SubmittedLeadsData = [
  {
    id: "1234",
    full_name: "Jerome Bell",
    homeowners_address: "123 Main St, Los Angeles",
    hmeowners_name: "David",
    hmeowners_phone: "+32 123123",
    trade: "Plumbing",
    lead_sent: "Feb 23, 2026",
  },
  {
    id: "1235",
    full_name: "Wade Warren",
    homeowners_address: "456 Oak Ave, New York",
    hmeowners_name: "Sarah",
    hmeowners_phone: "+32 456789",
    trade: "Electrical",
    lead_sent: "Feb 24, 2026",
  },
  {
    id: "1236",
    full_name: "Esther Howard",
    homeowners_address: "789 Pine Rd, Chicago",
    hmeowners_name: "Michael",
    hmeowners_phone: "+32 789012",
    trade: "Carpentry",
    lead_sent: "Feb 25, 2026",
  },
  {
    id: "1237",
    full_name: "Cameron Williamson",
    homeowners_address: "321 Elm Blvd, Houston",
    hmeowners_name: "Jennifer",
    hmeowners_phone: "+32 345678",
    trade: "HVAC",
    lead_sent: "Feb 26, 2026",
  },
  {
    id: "1238",
    full_name: "Brooklyn Simmons",
    homeowners_address: "654 Maple Ln, Phoenix",
    hmeowners_name: "Robert",
    hmeowners_phone: "+32 901234",
    trade: "Painting",
    lead_sent: "Feb 27, 2026",
  },
  {
    id: "1239",
    full_name: "Leslie Alexander",
    homeowners_address: "987 Cedar Dr, Philadelphia",
    hmeowners_name: "Lisa",
    hmeowners_phone: "+32 567890",
    trade: "Roofing",
    lead_sent: "Feb 28, 2026",
  },
  {
    id: "1240",
    full_name: "Jenny Wilson",
    homeowners_address: "147 Birch St, San Antonio",
    hmeowners_name: "James",
    hmeowners_phone: "+32 112233",
    trade: "Landscaping",
    lead_sent: "Mar 1, 2026",
  },
  {
    id: "1241",
    full_name: "Kristin Watson",
    homeowners_address: "258 Spruce Ave, San Diego",
    hmeowners_name: "Patricia",
    hmeowners_phone: "+32 445566",
    trade: "Masonry",
    lead_sent: "Mar 2, 2026",
  },
  {
    id: "1242",
    full_name: "Guy Hawkins",
    homeowners_address: "369 Willow Rd, Dallas",
    hmeowners_name: "Thomas",
    hmeowners_phone: "+32 778899",
    trade: "Flooring",
    lead_sent: "Mar 3, 2026",
  },
  {
    id: "1243",
    full_name: "Floyd Miles",
    homeowners_address: "741 Poplar Ln, San Jose",
    hmeowners_name: "Linda",
    hmeowners_phone: "+32 990011",
    trade: "Windows",
    lead_sent: "Mar 4, 2026",
  },
  {
    id: "1244",
    full_name: "Dianne Russell",
    homeowners_address: "852 Ash Ct, Austin",
    hmeowners_name: "Charles",
    hmeowners_phone: "+32 223344",
    trade: "Insulation",
    lead_sent: "Mar 5, 2026",
  },
  {
    id: "1245",
    full_name: "Jerome Bell",
    homeowners_address: "963 Beech Way, Jacksonville",
    hmeowners_name: "Barbara",
    hmeowners_phone: "+32 556677",
    trade: "Drywall",
    lead_sent: "Mar 6, 2026",
  },
  {
    id: "1246",
    full_name: "Marvin McKinney",
    homeowners_address: "159 Sycamore St, Fort Worth",
    hmeowners_name: "Joseph",
    hmeowners_phone: "+32 889900",
    trade: "Tile",
    lead_sent: "Mar 7, 2026",
  },
  {
    id: "1247",
    full_name: "Devon Lane",
    homeowners_address: "753 Magnolia Dr, Columbus",
    hmeowners_name: "Margaret",
    hmeowners_phone: "+32 112244",
    trade: "Concrete",
    lead_sent: "Mar 8, 2026",
  },
  {
    id: "1248",
    full_name: "Courtney Henry",
    homeowners_address: "951 Hickory Blvd, Charlotte",
    hmeowners_name: "Daniel",
    hmeowners_phone: "+32 335577",
    trade: "Fencing",
    lead_sent: "Mar 9, 2026",
  },
];