export const usersData = [
    {
        userId: '1234',
        name: 'Jerome Bell',
        trade: 'Plumbing',
        last_lead_he_sent: 'Feb 17, 2026',
        total_leads_he_sent: 20,
        last_connection_we_sent: 'Feb 17, 2026',
    },
    {
        userId: '1235',
        name: 'Wade Warren',
        trade: 'Electrical',
        last_lead_he_sent: 'Feb 18, 2026',
        total_leads_he_sent: 15,
        last_connection_we_sent: 'Feb 18, 2026',
    },
    {
        userId: '1236',
        name: 'Esther Howard',
        trade: 'Carpentry',
        last_lead_he_sent: 'Feb 19, 2026',
        total_leads_he_sent: 12,
        last_connection_we_sent: 'Feb 19, 2026',
    },
    {
        userId: '1237',
        name: 'Cameron Williamson',
        trade: 'HVAC',
        last_lead_he_sent: 'Feb 20, 2026',
        total_leads_he_sent: 18,
        last_connection_we_sent: 'Feb 20, 2026',
    },
    {
        userId: '1238',
        name: 'Brooklyn Simmons',
        trade: 'Painting',
        last_lead_he_sent: 'Feb 21, 2026',
        total_leads_he_sent: 10,
        last_connection_we_sent: 'Feb 21, 2026',
    },
    {
        userId: '1239',
        name: 'Leslie Alexander',
        trade: 'Roofing',
        last_lead_he_sent: 'Feb 22, 2026',
        total_leads_he_sent: 22,
        last_connection_we_sent: 'Feb 22, 2026',
    },
    {
        userId: '1240',
        name: 'Jenny Wilson',
        trade: 'Landscaping',
        last_lead_he_sent: 'Feb 23, 2026',
        total_leads_he_sent: 8,
        last_connection_we_sent: 'Feb 23, 2026',
    },
    {
        userId: '1241',
        name: 'Kristin Watson',
        trade: 'Masonry',
        last_lead_he_sent: 'Feb 24, 2026',
        total_leads_he_sent: 14,
        last_connection_we_sent: 'Feb 24, 2026',
    },
    {
        userId: '1242',
        name: 'Guy Hawkins',
        trade: 'Flooring',
        last_lead_he_sent: 'Feb 25, 2026',
        total_leads_he_sent: 11,
        last_connection_we_sent: 'Feb 25, 2026',
    },
    {
        userId: '1243',
        name: 'Floyd Miles',
        trade: 'Windows',
        last_lead_he_sent: 'Feb 26, 2026',
        total_leads_he_sent: 9,
        last_connection_we_sent: 'Feb 26, 2026',
    },
    {
        userId: '1244',
        name: 'Dianne Russell',
        trade: 'Insulation',
        last_lead_he_sent: 'Feb 27, 2026',
        total_leads_he_sent: 13,
        last_connection_we_sent: 'Feb 27, 2026',
    },
    {
        userId: '1245',
        name: 'Jerome Bell',
        trade: 'Drywall',
        last_lead_he_sent: 'Feb 28, 2026',
        total_leads_he_sent: 16,
        last_connection_we_sent: 'Feb 28, 2026',
    },
    {
        userId: '1246',
        name: 'Marvin McKinney',
        trade: 'Tile',
        last_lead_he_sent: 'Mar 1, 2026',
        total_leads_he_sent: 7,
        last_connection_we_sent: 'Mar 1, 2026',
    },
    {
        userId: '1247',
        name: 'Devon Lane',
        trade: 'Concrete',
        last_lead_he_sent: 'Mar 2, 2026',
        total_leads_he_sent: 19,
        last_connection_we_sent: 'Mar 2, 2026',
    },
    {
        userId: '1248',
        name: 'Courtney Henry',
        trade: 'Fencing',
        last_lead_he_sent: 'Mar 3, 2026',
        total_leads_he_sent: 17,
        last_connection_we_sent: 'Mar 3, 2026',
    },
];